### ISSUE TITLE
question about Gait Recognition

### ISSUE THREAD

**Issue by Graysonggg** [tinyvision/SOLIDER#11]
Great job! 
I would like to ask a question: 
I don't see Gait Recognition task in the mentioned six downstream tasks, is SOLIDER not suitable for processing human gait features based on silhouette? , or is it out of some other consideration?
Look forward to receiving your reply, thank you.

**Comment by cwhgn** [comment]
Thanks for your interests! We believe the SOLIDER would provide some helps for the silhouette information in gait features as well as it does on reid. The reason of missing Gait Recognition task in current version is because that current SOLIDER mainly focuses on image-level task. Thanks for your advice. We agree the extension on video/sequence-level tasks is a good way to further verify the effectiveness of SOLIDER.
